# Generated by Django 5.0.3 on 2024-03-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_alter_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена'),
        ),
    ]
